export const types = {
    FETCH_TODOS: 'FETCH_TODOS',
    VISIBILITY_FILTER: 'VISIBILITY_FILTER',
    ADD_TODO: 'ADD_TODO',
    DELETE_TODO: 'DELETE_TODO',
    MOVE_TODO: 'MOVE_TODO',
    LOADING: 'LOADING',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    REGISTER_SUCCESS: 'REGISTER_SUCCESS',
    FIREBASE_LOADED: 'FIREBASE_LOADED',
    LOGOUT: 'LOGOUT'
}
